#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clear_IBUF]

set_property PACKAGE_PIN D4 [get_ports {clk_50m}]
        set_property IOSTANDARD LVCMOS33 [get_ports {clk_50m}]
set_property PACKAGE_PIN T8 [get_ports {shift}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {shift}]
                       
                        
#VGA Connector
set_property PACKAGE_PIN F5 [get_ports {vga_r[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN F4 [get_ports {vga_r[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN M16 [get_ports {vga_r[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN M15 [get_ports {vga_r[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN R16 [get_ports {vga_b[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN T15 [get_ports {vga_b[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN P14 [get_ports {vga_b[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN T14 [get_ports {vga_b[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN N16 [get_ports {vga_g[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN P15 [get_ports {vga_g[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN P16 [get_ports {vga_g[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN R15 [get_ports {vga_g[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN R13 [get_ports vga_hsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property PACKAGE_PIN T13 [get_ports vga_vsync]						
	set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]
	
##Buttons
    set_property PACKAGE_PIN K3 [get_ports {row[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
    set_property PACKAGE_PIN M6 [get_ports {row[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
    set_property PACKAGE_PIN P10 [get_ports {row[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
    set_property PACKAGE_PIN R10 [get_ports {row[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
        
    set_property PACKAGE_PIN R12 [get_ports {col[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
    set_property PACKAGE_PIN T12 [get_ports {col[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
    set_property PACKAGE_PIN R11 [get_ports {col[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
    set_property PACKAGE_PIN T10 [get_ports {col[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
    set_property PULLDOWN true [get_ports {col[3]}]
    set_property PULLDOWN true [get_ports {col[2]}]
    set_property PULLDOWN true [get_ports {col[1]}]
    set_property PULLDOWN true [get_ports {col[0]}]

## Switches
set_property PACKAGE_PIN T9 [get_ports {btn_rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_rst_n}]
# set_property PACKAGE_PIN T8 [get_ports {delete}]
# set_property IOSTANDARD LVCMOS33 [get_ports {delete}]
# set_property PACKAGE_PIN T7 [get_ports {wrPos_add}]
# set_property IOSTANDARD LVCMOS33 [get_ports {wrPos_add}]
# set_property PACKAGE_PIN R6 [get_ports {wrPos_sub}]
# set_property IOSTANDARD LVCMOS33 [get_ports {wrPos_sub}]

set_property PACKAGE_PIN F3 [get_ports {colorIndexB[3]}]				
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexB[3]}]
set_property PACKAGE_PIN H4 [get_ports {colorIndexB[2]}]				
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexB[2]}]
set_property PACKAGE_PIN N4 [get_ports {colorIndexB[1]}]				
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexB[1]}]
set_property PACKAGE_PIN R2 [get_ports {colorIndexB[0]}]				
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexB[0]}]                        
set_property PACKAGE_PIN R3 [get_ports {colorIndexF[3]}]				
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexF[3]}]
set_property PACKAGE_PIN P4 [get_ports {colorIndexF[2]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexF[2]}]
set_property PACKAGE_PIN R5 [get_ports {colorIndexF[1]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexF[1]}]
set_property PACKAGE_PIN P6 [get_ports {colorIndexF[0]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {colorIndexF[0]}]       
##led
set_property PACKAGE_PIN P9 [get_ports {led[0]}]
set_property PACKAGE_PIN R8 [get_ports {led[1]}]
set_property PACKAGE_PIN R7 [get_ports {led[2]}]
set_property PACKAGE_PIN T5 [get_ports {led[3]}]
set_property PACKAGE_PIN N6 [get_ports {led[4]}]
set_property PACKAGE_PIN T4 [get_ports {led[5]}]
set_property PACKAGE_PIN T3 [get_ports {led[6]}]
set_property PACKAGE_PIN T2 [get_ports {led[7]}]
set_property PACKAGE_PIN R1 [get_ports {led[8]}]
set_property PACKAGE_PIN G5 [get_ports {led[9]}]
set_property PACKAGE_PIN H3 [get_ports {led[10]}]
set_property PACKAGE_PIN E3 [get_ports {led[11]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

#IO
set_property PACKAGE_PIN E12 [get_ports {xKeys[0]} ]
set_property PACKAGE_PIN D13 [get_ports {xKeys[1]} ]
set_property PACKAGE_PIN D11 [get_ports {xKeys[2]} ]
set_property PACKAGE_PIN E11 [get_ports {xKeys[3]} ]
set_property PACKAGE_PIN B14 [get_ports {xKeys[4]} ]
set_property PACKAGE_PIN C12 [get_ports {xKeys[5]} ]
set_property PACKAGE_PIN B12 [get_ports {xKeys[6]} ]
set_property PACKAGE_PIN A10 [get_ports {xKeys[7]} ]
set_property PACKAGE_PIN A9 [get_ports {xKeys[8]} ]
set_property PACKAGE_PIN C8 [get_ports {xKeys[9]} ]
set_property PACKAGE_PIN C6 [get_ports {xKeys[10]} ]
set_property PACKAGE_PIN D5 [get_ports {xKeys[11]} ]
set_property PACKAGE_PIN C4 [get_ports {xKeys[12]} ]
set_property PACKAGE_PIN B7 [get_ports {xKeys[13]} ]
set_property PACKAGE_PIN A5 [get_ports {xKeys[14]} ]
set_property PACKAGE_PIN A4 [get_ports {xKeys[15]} ]
set_property PACKAGE_PIN D3 [get_ports {xKeys[16]} ]

set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[0]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[1]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[2]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[3]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[4]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[5]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[6]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[7]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[8]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[9]} ]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xKeys[16]}]

set_property PULLDOWN true [get_ports {xKeys[0]} ]
set_property PULLDOWN true [get_ports {xKeys[1]} ]
set_property PULLDOWN true [get_ports {xKeys[2]} ]
set_property PULLDOWN true [get_ports {xKeys[3]} ]
set_property PULLDOWN true [get_ports {xKeys[4]} ]
set_property PULLDOWN true [get_ports {xKeys[5]} ]
set_property PULLDOWN true [get_ports {xKeys[6]} ]
set_property PULLDOWN true [get_ports {xKeys[7]} ]
set_property PULLDOWN true [get_ports {xKeys[8]} ]
set_property PULLDOWN true [get_ports {xKeys[9]} ]
set_property PULLDOWN true [get_ports {xKeys[10]}]
set_property PULLDOWN true [get_ports {xKeys[11]}]
set_property PULLDOWN true [get_ports {xKeys[12]}]
set_property PULLDOWN true [get_ports {xKeys[13]}]
set_property PULLDOWN true [get_ports {xKeys[14]}]
set_property PULLDOWN true [get_ports {xKeys[15]}]
set_property PULLDOWN true [get_ports {xKeys[16]}]